### ISSUE TITLE
NetBeans Problem

### ISSUE THREAD

**Issue by LynSisCZ** [compwiz1548/SlackMC#5]
Hello can you help me with import your source code to netbeans please ? Or in which program you are writing ?

**Comment by compwiz1548** [comment]
I use IntelliJ IDEA, personally. If you use that, just fork and clone the repo, then run `gradlew setupDecompWorkspace idea` and the dev environment will be setup. Once it's done, you just open the project in IDEA.

**Comment by LynSisCZ** [comment]
Ok thank you :)
